site_name: AppDynamics Release Notes

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
pages:
- Mobile Agents: 'index.md'
- iOS Agent:
    - '4.3.1': 'ios-agent/4.3.1.md'
    - '4.3.2': 'ios-agent/4.3.2.md'
    - '4.3.3': 'ios-agent/4.3.3.md'
- Android Agent:
    - '4.3.1': 'android-agent/4.3.1.md'
    - '4.3.2': 'android-agent/4.3.2.md'
    - '4.3.3': 'android-agent/4.3.3.md'

